### ISSUE TITLE
A1469 and tvOS8.4.4, Jailbreak Completes but no new applications

### ISSUE THREAD

**Issue by lestat1977uk** [NSSpiral/Blackb0x#51] opened 2021-08-07 04:37 UTC
A1469
tvOS8.4.4
Blackb0x 0.5

Hi All, 

First of all thanks for making this software would be great to make use of my old ATV3 box, unfortunately, although the jailbreak completes and then asks me to unplug the USB, connect the TV and wait for it to restart, it never restarts, i have left it for several hours.

I always need to resort to triggering a manual restart (i have done this jb 3 times, restoring to factory between each attempt)

Below is my log I hope you can help.

Starting post-install
Adding replacement default repository
Installing JoshTV Repo
Updating apt
Update failed
Stashing directories
Installing debs
Installing substrate
Upgrade failed
Installing nitoTV
Installing Kodi
Install AFC2
Finished installation

Thanks 

Wes

**Comment by DavidBanuta** [comment] 2021-08-07 09:56
I face the same issue. Is there any way to solve it?

**Comment by HoSpeLL** [comment] 2021-08-08 17:09
Just leave the AppleTV on for 5-10 minutes after jailbreaking it and the apps will appear

**Comment by NSSpiral** [comment] 2021-08-09 02:40
The domain for joshtv.net repo is expired. I'm trying to get in contact with him to renew it. It's needed to set up the Apple TV.

**Comment by dannyboyswe** [comment] 2021-08-11 16:48
I had to borrow a Mac to do this jailbreak, and noticed the exact same thing, no Kodi shows up. Will I need to redo the jailbreak when the repo is back online, or can I just power it on (with ethernet connected) and let it do its thing installing Kodi, even if that's three weeks from now (I'm just speculating on the time frame)?

**Comment by lestat1977uk** [comment] 2021-08-12 03:19
Any update on this, did he respond?

**Comment by NSSpiral** [comment] 2021-08-12 06:01
Haven't been able to contact him yet, might have to get an alternative
hosted.

**Comment by lestat1977uk** [comment] 2021-08-15 01:15
Any news on an alternative, or an alternative way to install Kodi now we have jailbroken our devices?

**Comment by jrgadgets** [comment] 2021-08-15 05:51
> A1469
> tvOS8.4.4
> Blackb0x 0.5
> 
> Hi All,
> 
> First of all thanks for making this software would be great to make use of my old ATV3 box, unfortunately, although the jailbreak completes and then asks me to unplug the USB, connect the TV and wait for it to restart, it never restarts, i have left it for several hours.
> 
> I always need to resort to triggering a manual restart (i have done this jb 3 times, restoring to factory between each attempt)
> 
> Below is my log I hope you can help.
> 
> Starting post-install
> Adding replacement default repository
> Installing JoshTV Repo
> Updating apt
> Update failed
> Stashing directories
> Installing debs
> Installing substrate
> Upgrade failed
> Installing nitoTV
> Installing Kodi
> Install AFC2
> Finished installation
> 
> Thanks
> 
> Wes

Hi having the same issues

**Comment by 2an2an2** [comment] 2021-08-17 19:06
same issue here

**Comment by dannyboyswe** [comment] 2021-08-18 13:56
There is a recent snapshot of JoshTV over at Wayback Machine, but I'm guessing it's not as easy as just redirecting the trafic over there instead?
http://web.archive.org/web/20210616033408/https://joshtv.net/

**Comment by Punteillos** [comment] 2021-08-19 11:44
Hi, same here, i try to jailbreak and all works well but no reboot, when i reboot manually and wait even 30min to see the new kodi icon it dont appear...

BUT!: I have ssh connection, and i spend 3 days to try to install all mannually but i can not do it becaouse dependencies.

I Think the problem is just with: josh.tv site, its actually down.

Please Fix it, or if someone can tell me how to install kodi across ssh... i try almoust everything.

**Comment by opengrads** [comment] 2021-08-20 01:34
Same here. Any way to install Kodi, Nito by hand via ssh?

**Comment by raghu-mp** [comment] 2021-08-24 14:50
Try the following steps.

1. Connect via SSH 
2. apt-get dist-upgrade -V      -- Make sure apt7-ssl package is removed as it causes problems with apt-get update after adding the repo for Nito and Kodi. Run dpkg -l to view the install package list.
3. wget -O- http://apt.awkwardtv.org/awkwardtv.pub | apt-key add -
4. echo "deb http://apt.awkwardtv.org/ stable main" > /etc/apt/sources.list.d/awkwardtv.list
5. apt-get update
6. apt-get -y install com.nito.nitoTV 
7. apt-get -y install org.xbmc.kodi-atv2
8. uicache

The latest version Kodi is 14.2 which is pretty useless now as most addons don't work.

**Comment by dannyboyswe** [comment] 2021-08-24 17:59
>     2\. dpkg -l

I couldn't get this to work.

**Comment by Vipizz** [comment] 2021-08-24 19:17
This is actually working! thanks raghu-mp

Can confirm this working 2021-08-24 21:00 on 2 ATV 3.1

Do this after jailbreak and logon into ssh to the ATV
run:

apt-get -y dist-upgrade -V --
rm /etc/apt/sources.list.d/joshtv.list
wget -O- http://apt.awkwardtv.org/awkwardtv.pub | apt-key add -
echo "deb http://apt.awkwardtv.org/ stable main" > /etc/apt/sources.list.d/awkwardtv.list
apt-get update
apt-get -y install com.nito.nitoTV --force-yes
apt-get -y install org.xbmc.kodi-atv2 --force-yes
uicache

I got no icon on kodi, fix this by running:
/bin/mv /kodi.png /private/var/stash/Applications/AppleTV.app/com.apple.frontrow.appliance.kodi\@1080.png
killall -9 backboardd

;)

**Comment by raghu-mp** [comment] 2021-08-24 19:59
Glad it worked! If anyone figures out how to get a better version of Kodi, please share. I have been searching and trying different methods to no avail. Installation of iphoneos-arm.deb works, but it shows up as Kodi.app along with the atv2 version which is already installed as Kodi.frappliance. 

When atv2 is installed it creates the following symlink.

lrwxr-xr-x 1 root wheel  30 Aug 24 15:54 Kodi.frappliance -> /Applications/Kodi.frappliance

Tried re-pointing this symlink to /Applications/Kodi.app. But that does not work. I have concluded that newer version of Kodi must be compiled for Apple TV 3.

**Comment by felipefrancc** [comment] 2021-08-25 06:09
I'm getting an error when doing the 3rd step, something to do with SSL but not sure what, pasted bellow is what I got:

Apple-TV:~ root# wget -O- http://apt.awkwardtv.org/awkwardtv.pub | apt-key add -
--2021-08-24 22:57:55--  http://apt.awkwardtv.org/awkwardtv.pub
Resolving apt.awkwardtv.org... 155.138.254.229
Connecting to apt.awkwardtv.org|155.138.254.229|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://apt.awkwardtv.org/awkwardtv.pub [following]
--2021-08-24 22:57:55--  https://apt.awkwardtv.org/awkwardtv.pub
Connecting to apt.awkwardtv.org|155.138.254.229|:443... connected.
OpenSSL: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number
Unable to establish SSL connection.
gpg: no valid OpenPGP data found.
Apple-TV:~ root#

Again I don't really know why this is happening or what the error actually is

**Comment by raghu-mp** [comment] 2021-08-25 13:26
@felipefrancc  
This happens if step 2 did not work correctly. Check that step once again and make sure apt7-ssl package has been removed after the dist-upgrade.

**Comment by Dirgible** [comment] 2021-08-31 04:44
I have the a1469, and used the Blackb0x jailbreak and holding down and menu, then down and play / pause immediately afterward to enter DFU mode.  joshtv.net is confirmed busted, but the steps raghu-mp laid out worked excellently, except adding the public key (step 3), which it seems to be fine without.  ssh is done by root as user, and ip address as given out by your router (ssh root@192.168.x.x) with the password being alpine

Anyways, thanks for the help raghu-mp and all the rest, just wanted to summarize what I did that was successful.

**Comment by Byte2020** [comment] 2021-09-06 12:11
How do I logon into ssh ?
Getting this port 22: Connection refused
Thanks for help

**Comment by PrincipeAzzurro** [comment] 2021-09-11 03:38
Thank you raghu-mp and Vipizz for guiding us through the installation of the new sources. It worked well on my A1469, and the installed Kodi version is 14.2. 

Now the only question I have is this:
how can I update Kodi to a more recent version? I mean, how can I UPDATE Kodi? 

Thank you!!!

**Comment by raghu-mp** [comment] 2021-09-13 13:38
@PrincipeAzzurro - The highest Kodi version that is available for this version of AppleTV is 14.2. Unless someone can compile the more recent version (18.9 or 19.1), we are out of luck at the moment.

**Comment by kaanndagci** [comment] 2021-10-03 09:55
@raghu-mp how can i delete apt7-ssl?

**Comment by kaanndagci** [comment] 2021-10-03 10:27
@raghu-mp 
i have problem;
Apple-TV:~ root# wget -O- http://apt.awkwardtv.org/awkwardtv.pub | apt-key add -                                                                                                                           
--2021-10-03 13:25:44--  http://apt.awkwardtv.org/awkwardtv.pub
Resolving apt.awkwardtv.org... 155.138.254.229
Connecting to apt.awkwardtv.org|155.138.254.229|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://apt.awkwardtv.org/awkwardtv.pub [following]
--2021-10-03 13:25:48--  https://apt.awkwardtv.org/awkwardtv.pub
Connecting to apt.awkwardtv.org|155.138.254.229|:443... connected.
OpenSSL: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number
Unable to establish SSL connection.
gpg: no valid OpenPGP data found.

I deleted apt 7-ssl, but I have such a problem, how can I solve it?

**Comment by fantas21** [comment] 2021-10-03 19:19
> @raghu-mp Apple TV 3rd generation (2013) firmware: 8.4.6
> 
> i have problem; Apple-TV:~ root# wget -O- http://apt.awkwardtv.org/awkwardtv.pub | apt-key add - --2021-10-03 13:25:44-- http://apt.awkwardtv.org/awkwardtv.pub Resolving apt.awkwardtv.org... 155.138.254.229 Connecting to apt.awkwardtv.org|155.138.254.229|:80... connected. HTTP request sent, awaiting response... 302 Found Location: https://apt.awkwardtv.org/awkwardtv.pub [following] --2021-10-03 13:25:48-- https://apt.awkwardtv.org/awkwardtv.pub Connecting to apt.awkwardtv.org|155.138.254.229|:443... connected. OpenSSL: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number Unable to establish SSL connection. gpg: no valid OpenPGP data found.
> 
> I deleted apt 7-ssl, but I have such a problem, how can I solve it?

This procedure is for appletv 2nd generation. The ATV2 only works on 2nd generation.

**Comment by kaanndagci** [comment] 2021-10-03 20:22
@fantas21 hmm...

How can i download kodi tv on my atv3,2 ?

**Comment by NSSpiral** [comment] 2021-12-20 01:35
Newest build should install Kodi automatically again

**Closed by NSSpiral** 2021-12-20 01:35 UTC

**Comment by Carnarts** [comment] 2022-06-10 20:36
I can't seem to install kodi, I can SSH into root of Apple tv but when I try:
wget -O- http://apt.awkwardtv.org/awkwardtv.pub | apt-key add -

it gives me:

Connecting to apt.awkwardtv.org|155.138.254.229|:80... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

until it gives up...any ideas?

**Comment by Carnarts** [comment] 2022-06-11 15:06
Ok I got it working finally after several attempts with a fresh jailbreak and Kodi loaded by itself. 
Transferring videos onto the ATV with Filezilla works pretty well so far, but not sure of the best codecs to use. I am planning on using it for a video art media player.
